### ISSUE TITLE
Broken initial clash configuration is blocking the networking after first installation.

### ISSUE THREAD

**Issue by ghost** [LEXUGE/nixos#2]
I am having trouble with networking, both wifi and cable after install. I am connected to SSID but no connection. 
Couple things:
The install script failed with default nixos username so I changed to root with `sudo su -` 
Then I had to `curl -Ls ... > install.sh`  and `chmod u+x install.sh` then modify to just use nixos binary caches. After install I couldn't login, no password I previously used worked. I installed again but this time I added `initialPassword = "passphrase";` to `ash.nix`. I could login then. Now I have no access to internet even though nmcli is connected to my SSID. What seems to be the issue? How to update the system, I cannot do `nixos-rebuild switch` because it is trying to connect to home-manager repository. I am still quite new with Nixos. Thank you for putting this together, it is a great learning ground!

**Comment by LEXUGE** [comment]
emmm, that could be weird. Could you please detail your hardware information?

**Comment by LEXUGE** [comment]
Oh, I know, you would probably look into clash configuration for a moment.
Try this for `/etc/secrets/clash.yaml`
```yaml
# port of SOCKS5
socks-port: 7891

# redir port for Linux and macOS
redir-port: 7892

allow-lan: false

# Rule / Global / Direct (default is Rule)
mode: Rule

# set log level to stdout (default is info)
# info / warning / error / debug / silent
log-level: info

# RESTful API for clash
external-controller: 127.0.0.1:9090

# experimental feature
experimental:
  ignore-resolve-fail: true # ignore dns resolve fail, default value is true
  # interface-name: en0 # outbound interface name

dns:
  enable: true
  listen: 127.0.0.1:53
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - tls://1.1.1.1:853
    - https://cloudflare-dns.com/dns-query
    - tls://dns.google

rules:
  # Proxy rest of the inquiries
  - MATCH,DIRECT
```

Then `systemctl restart clash`.

I suggest you to look into the detailed information about clash. It is quite versatile, but above should make system work (although not work in an elegant way).

I am working on a framework which could make my configuration here hot-pluggable and reusable in other configuration, stay tuned.
